# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cbcf8af5cb1cd3e3cf072a68533273133c7fb149961215038ba4a5fac6cb1ba3afe6177cf5b11e5ca4ee61c565a0f2897f02662d78d5230cbf87cea3b67d800

test:
  secret_key_base: 7191aef80026e2da305aeb2682a3b6efd285ff44b852f334a9c60aaa27529708985bf097ff928d9013034336cea393252e50e4cb9d2d60dbdfc6f1d43c98364a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
